[project]
name = "yokokanovelextractor-fromline"
version = "0.1.0"
description = "A tool to extract Yokoka novel from LINE chat history."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
